export {default as Base} from './Base'
export {default as Container} from './Container'
export {default as Grid} from './Grid'
export {default as List} from './List'
export {default as Media} from './Media'
export {default as Type} from './Type'
export {default as H1} from './H1'
export {default as H2} from './H2'
export {default as H3} from './H3'
export {default as H4} from './H4'
export {default as H5} from './H5'
export {default as H6} from './H6'
export {default as P} from './P'

import * as ReactIota from '.'
export default ReactIota
